apiVersion: v1
kind: Template
labels:
  template: bc-paris-api-service-template
metadata:
  annotations:
    openshift.io/display-name: BC Paris Service Template
    description: |-
      This is a template for an OpenShift Service.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: service-template
parameters:
  - description: The name assigned to all of the frontend objects defined in this template.
    displayName: Name
    name: appName
    required: true
    value: bc-paris-api
  - description: Openshift namespace prefix
    displayName: Namespace Prefix
    name: namespacePrefix
    required: true
    value: xqb2qz
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Exposes and load balances the application pods
        kubectl.kubernetes.io/last-applied-configuration: >
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"description":"Exposes
          and load balances the application
          pods"},"labels":{"app":"bc-paris-api","template":"meta-service"},"name":"bc-paris-api","namespace":"xqb2qz-dev"},"spec":{"ports":[{"name":"web","port":80,"targetPort":8080}],"selector":{"deployment":"bc-paris-api"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      labels:
        app: ${appName}
        template: meta-service
      name: ${appName}
      namespace: ${namespacePrefix}-dev
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deployment: ${appName}  
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}

