apiVersion: v1
kind: Service
metadata:
  labels:
    app: bc-paris-api-oauth
  name: bc-paris-api-oauth
  namespace: 91beaa-test
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bc-paris-api-oauth
  sessionAffinity: None
  type: ClusterIP
