# Used to trigger deployment to dev, test & prod Openshift environnment by Image stream re-tagging and labelling pod

name: Trigger deployment to dev, test & prod Openshift environnment by Image stream re-tagging and labelling pod

on:        
    workflow_dispatch:
        inputs:
            app:
                description: 'App Name (bc-paris-api)'    
                required: true
                default: 'bc-paris-api'
            imageSourceEnv:
                description: 'Image Source Env'     
                required: true
                default: 'latest'
            imageTargetEnv:
                description: 'Target Release Env'
                required: true
                default: 'dev'

jobs:

  promote-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-tag-image.yml@main
    with:
      image_stream_name: ${{ github.event.inputs.app }}
      source_image_tag: ${{ github.event.inputs.imageSourceEnv }}
      image_tags: ${{ github.event.inputs.imageTargetEnv }}
    secrets:
      openshift_namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
      openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}
  
  git-commitversion:
    uses: SierraSystems/reusable-workflows/.github/workflows/get-github-commitversion.yml@main
    with:
      working_directory: .

  backup-image:
    if: ${{ (github.event.inputs.imageTargetEnv != 'dev') }}
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-tag-image.yml@main
    needs:
      - git-commitversion
    with:
      image_stream_name: ${{ github.event.inputs.app }}
      source_image_tag: ${{ github.event.inputs.imageSourceEnv }}
      image_tags: ${{ needs.git-commitversion.outputs.github-release-version }}
    secrets:
      openshift_namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
      openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}

  label-pods:
    if: ${{ (github.event.inputs.imageTargetEnv != 'dev') }}
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-dc-pods-labelling.yml@main
    needs:
      - git-commitversion
    with:
      app: ${{ github.event.inputs.app }}
      target_env: ${{ github.event.inputs.imageTargetEnv }}
      label: ${{ needs.git-commitversion.outputs.github-release-version }}
    secrets:
      openshift_namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
      openshift_sa_env_deployer_token: ${{ secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN }}
