name: Build & Vulnerability Scan using Trivy Scanner

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]

jobs:
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK for Maven
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Clean and build the app using Maven
      - name: Maven Package
        run: mvn -ntp clean package -Popenshift -DskipTests

      # Build Docker image without cache to avoid stale content
      - name: Build Docker image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: .
        run: |
          docker rmi bc-paris-api:${{ github.sha }} || true
          docker build --no-cache -t bc-paris-api:${{ github.sha }} ${CONTEXT}

      # Confirm image was built successfully
      - name: List Docker images
        run: docker images | grep bc-paris-api

      # Run vulnerability scan using Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.2
        with:
          scan-type: image
          image-ref: bc-paris-api:${{ github.sha }}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      # Upload scan results to GitHub Security tab
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: trivy-results.sarif
